spring:
  application:
    name: ex0910_jpa1
  datasource:
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: 11111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
        hibernate:
            format_sql: true
            