/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pm;

import java.awt.CardLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author 쌍용교육센터
 */
public class ChatFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChatFrame.class.getName());

    /**
     * Creates new form ChatFrame
     */
    
    CardLayout card;
    
    Socket s;
    ObjectInputStream in;
    ObjectOutputStream out;
    
    
    //서버쪽에서 데이터가 넘어오는지? 항상 감시하는 스레드
    Thread t = new Thread() {

		@Override
		public void run() {
			bk:while(true) {
				try {
					Object obj = in.readObject();//서버로부터 데이터가 올 때까지
												 //대기한다
					Protocol p = (Protocol) obj;
					
					switch(p.getCmd()) {
					case 1: //어떤 누군가가 접속했을 때 수행
						//명단을 받아서 user_list라는 JList에 넣어준다.
						user_list.setListData(p.getUser_names());
						break;
					case 3:
						System.out.println("누군가 종료함");
						user_list.setListData(p.getUser_names());
						break;
						
					}
					
					
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				
			}
		}
    	
    };
    
    public ChatFrame() {
        initComponents();//화면구성
        setVisible(true);//화면 보여주기
        
        
        //이벤트감지자 등록
        this.addWindowListener(new WindowAdapter() {

			@Override
			public void windowClosing(WindowEvent e) {
				// TODO Auto-generated method stub
				Protocol p = new Protocol();
				p.setCmd(3);
				
				try {
					out.writeObject(p);
					out.flush();
					t.stop();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
				System.exit(0);
			}
        	
		});
        
        jButton1.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				String n = jTextField1.getText().trim();
				if(n.length()<1) {
					JOptionPane.showMessageDialog(ChatFrame.this, "대화명을 입력하세요");
					jTextField1.setText("");
					jTextField1.requestFocus();//커서갖다놓기
					return;
				}else {
					//서버접속
					try {
						s = new Socket("192.168.10.102",5555);
						out = new ObjectOutputStream(s.getOutputStream());
						in = new ObjectInputStream(s.getInputStream());
						t.start();
						
						card.show(getContentPane(), "roomlist");
						//처음 접속했다는 의미로 프로토콜 데이터 보내야함
						Protocol p = new Protocol();
						p.setCmd(1);
						p.setMsg(n);//대화명
						
						//서버로 보낸다
						out.writeObject(p);
						out.flush();
						
					} catch (Exception e2) {
						// TODO: handle exception
						e2.printStackTrace();
					}
				}
			}
		});
		
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        card1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        card2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        user_list = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        room_list = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();

//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(card = new java.awt.CardLayout());

        card1.setLayout(new java.awt.BorderLayout());

        jLabel1.setMaximumSize(new java.awt.Dimension(437, 535));
        jLabel1.setMinimumSize(new java.awt.Dimension(437, 535));
        ImageIcon icon = new ImageIcon("src/images/chat.png");
        Image img = icon.getImage().getScaledInstance(437,535,Image.SCALE_SMOOTH);
        ImageIcon icon2 = new ImageIcon(img);
        jLabel1.setIcon(icon2);
        jLabel1.setPreferredSize(new java.awt.Dimension(437, 535));
        card1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel2.setText("대화명 :");
        jPanel2.add(jLabel2);

        jTextField1.setColumns(10);
        jPanel2.add(jTextField1);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setText("로그인");
        
        jPanel3.add(jButton1);

        jPanel1.add(jPanel3);

        card1.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(card1, "first");

        card2.setPreferredSize(new java.awt.Dimension(437, 535));
        card2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.GridLayout(4, 0));

        jButton2.setText("방 만들기");
        jPanel6.add(jButton2);

        jButton4.setText("쪽지 보내기");
        jPanel6.add(jButton4);

        jButton3.setText("방 참여");
        jPanel6.add(jButton3);

        jButton5.setText("종료");
        jPanel6.add(jButton5);

        jPanel4.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jLabel4.setText("[대기실]");
        jPanel4.add(jLabel4, java.awt.BorderLayout.NORTH);

        user_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { ""};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(user_list);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        card2.add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setLayout(new java.awt.BorderLayout());

        room_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(room_list);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel3.setText("[방목록]");
        jPanel5.add(jLabel3, java.awt.BorderLayout.NORTH);

        card2.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(card2, "roomlist");

        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
             
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new ChatFrame().setVisible(true));
        new ChatFrame();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel card1;
    private javax.swing.JPanel card2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList<String> room_list;
    private javax.swing.JList<String> user_list;
    // End of variables declaration//GEN-END:variables
}
