spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/my_db?characterEncoding=UTF-8
        username: root
        password: 11111111
        tomcat:
            max-active: 30
            max-idle: 20
            min-idle: 10