spring:
    profiles:
        active: dev #활성화는 application-dev.yml파일로 함.
        include: secret #이 문서 안에 application-secret.yml파일의 내용을 포함함
    application:
        name: ex0911_jwt
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
