services:
  mysql80:
    image: mysql:8.0
    container_name: mysql80
    networks:
      - sist_net
    volumes:
      - ./backend/db/conf.d:/etc/mysql/conf.d/mysql.cnf
      - ./backend/db/data:/var/lib/mysql
      - ./backend/db/initdb.d:/docker-entrypoint-initdb.d
    env_file: ./backend/db/.env
    ports:
      - 3307:3306
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - sist_net
    ports:
      - 8080:8080
    depends_on:
      - mysql80
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql80:3306/my_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=1111
      # JPA를 쓴다면 여기 속성이 들어가야함
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - sist_net
    ports:
      - 3000:3000
    # depends_on:
    #   - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - sist_net
    restart: always
    ports:
      - 80:80
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
networks:
  sist_net:
    driver: bridge


