## 개발용 설정
server:
    port: 8080

spring:
    output:
        ansi:
            enabled: always
    datasource:
        url: jdbc:mysql://localhost:3306/my_db
        username: root
        password: 11111111
        driver-class-name: com.mysql.cj.jdbc.Driver

custom:
    fileDirPath: 