spring:
  application:
    name: ex0918_bbs
  datasource:
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: 11111111
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    active: dev
    include: secret

  # Flyway 설정
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: false
    clean-disabled: false
    repair-on-migrate: true
    database-type: mysql

  jpa:
    hibernate:
      ddl-auto: validate # Flyway 사용 시 validate로 변경 (테이블 생성은 Flyway가 담당)
      #validate: 엔티티와 DB 스키마가 일치하는지 검증만 수행
    show-sql: true
    properties:
      hibernate:
        show_sql: true # 실행되는 SQL쿼리를 콘솔에 출력
        format_sql: true # SQL 출력 시 보기 좋게 들여쓰기.정렬
        use_sql_comments: true # SQL 로그에 주석 추가
logging:
  level:
    root: INFO # 전체 애플리케이션의 로그레벨을 INFO로 설정 / 아래 두개의 중간
    #DEBUG나 TRACE는 더 상세한 로그를 출력
    #Error은 최소한의 로그만 출력